const team = [
  "TBD",
  "AeroFox",
  "Best Devil",
  "Blood of Legend",
  "Blood thirsty",
  "Defender ",
  "Galaxy X World",
  "Gamer Esports",
  "Grand Up",
  "MIDNIGHT GAMING",
  "Power Pro Esport",
  "SPIRIT OF FIGHTT",
  "The King Fights",
  "THE WOLF ESPORTS",
  "XML Esport's",
  "YGN HOSHI",
  "ZAST PIXELS",
  "zombie of legend",
  "404 Gaming",
  "ACQ Academy",
  "ACQ Esport",
  "AI ESPORTS",
  "Ameritrade Rise",
  "Ancient_Artifict",
  "ANJIN GUILDS",
  "AQ Hoshi",
  "ARIES Esports",
  "Asgardian…",
  "Astos",
  "ATM Esports",
  "Atomax FIRE",
  "AXIS LEGEND",
  "AXIS LEGEND",
  "Baby Evil Academy",
  "black Cody",
  "BLACK EYE E-SPORT",
  "BlueShark esport ",
  "BRQ ESPORT",
  "CAMPIONS ARMY",
  "ChaoticAnonyMous",
  "Critical Genius",
  "DARKINET",
  "DEATH NOTE INTERNATIONAL",
  "Demon Off Dark",
  "Demonic Embracer",
  "Draconic Academy",
  "DRACONIC ESPORTS",
  "Draconic Female",
  "DxC",
  "Dynamic Aspirant",
  "Emperor of Dark(EOD)",
  "Enemy’s Nightmare",
  "Ewol Academy",
  "Execration",
  "experience ESP",
  "Fennec Esports..",
  "Five army",
  "Five Face Player",
  "Freedom IDN (FRD)",
  "GIEDI PRIME",
  "GOD REBORN",
  "GOKAIGERED",
  "Grad dragon",
  "Next GENERATION",
  "HELL FIRE Esport",
  "Hello kitty Z4",
  "Holly Homies",
  "Hydrogen Saga",
  "ICE GLORY",
  "IMPERIUM",
  "Inferno Phantom.",
  "Infinity-All Star",
  "Kabjak Esports",
  "King Of Legionn",
  "KKC E-SPORT",
  "Lancer Academy",
  "Leader Girl",
  "Leader Girl .",
  "Legend God Fox",
  "LightCon Esport",
  "LOGICAL ESPORT",
  "LOVE OF LOVE",
  "lower esport",
  "Never Overtime",
  "NEVER SURRENDER ",
  "GloryFox",
  "NoName Esport",
  "NOT THIS TIME",
  "OG Esports",
  "ONE CRIMINALX",
  "OVER DARKNESS FC",
  "Phoenix Eraa",
  "Prime Kids (PRME)",
  "PRIME XTREME ( XT)",
  "PRIME XTRME ( XE)",
  "QUANTUM KNIGHTS ",
  "Rage of Devil",
  "Raper Rex ",
  "RRT LITTER BOY",
  "Sayper Legends",
  "School Of Noobs",
  "Sl Ke Mnak Eng",
  "SOCIAL CREATOR",
  "SOON Media",
  "SPANKER DARK",
  "SQ Initial",
  "Strong Boys",
  "super ultra  goat",
  "Supreme Serpent ",
  "TeamMaxPixies",
  "TG Esports ",
  "The Boys Esport",
  "THE NEWERA",
  "The PhoenixZ (TPX)",
  "The x Legend",
  "TG gaming",
  "TheDarkFalcon",
  "TheThunderlight",
  "TITAN ESPORT",
  "Unstuck In Time",
  "Veteran Esport",
  "VICIOUS BETA",
  "VICIOUS Immortal",
  "VICIOUS ROOKIE",
  "Warrior Esport ",
  "WE PLAYERS",
  "Wiseman Esport",
  "WuDang Academy",
  "ZD ESPORT",
];
const date = [
  "TBD",
  "18/Mar",
  "19/Mar",
  "20/Mar",
  "21/Mar",
  "25/Mar",
  "26/Mar",
  "27/Mar",
  "28/Mar",
];
const time = [
  "TBD",
  "6:00 PM",
  "6:30 PM",
  "7:00 PM",
  "7:30 PM",
  "8:00 PM",
  "8:30 PM",
  "9:00 PM",
  "9:30 PM",
];
const matches = [
  {
    id: "A1",
    date: date[1],
    time: time[1],
    team1: team[1],
    team2: team[128],
    winner: team[0],
  },
  {
    id: "A2",
    date: date[1],
    time: time[2],
    team1: team[64],
    team2: team[65],
    winner: team[0],
  },
  {
    id: "A3",
    date: date[1],
    time: time[3],
    team1: team[32],
    team2: team[97],
    winner: team[0],
  },
  {
    id: "A4",
    date: date[1],
    time: time[4],
    team1: team[33],
    team2: team[96],
    winner: team[0],
  },
  {
    id: "A5",
    date: date[1],
    time: time[5],
    team1: team[16],
    team2: team[113],
    winner: team[0],
  },
  {
    id: "A6",
    date: date[1],
    time: time[6],
    team1: team[49],
    team2: team[80],
    winner: team[0],
  },
  {
    id: "A7",
    date: date[1],
    time: time[7],
    team1: team[17],
    team2: team[112],
    winner: team[0],
  },
  {
    id: "A8",
    date: date[1],
    time: time[8],
    team1: team[48],
    team2: team[81],
    winner: team[0],
  },
  {
    id: "A9",
    date: date[2],
    time: time[1],
    team1: team[8],
    team2: team[121],
    winner: team[0],
  },
  {
    id: "A10",
    date: date[2],
    time: time[2],
    team1: team[57],
    team2: team[72],
    winner: team[0],
  },
  {
    id: "A11",
    date: date[2],
    time: time[3],
    team1: team[25],
    team2: team[104],
    winner: team[0],
  },
  {
    id: "A12",
    date: date[2],
    time: time[4],
    team1: team[40],
    team2: team[89],
    winner: team[0],
  },
  {
    id: "A13",
    date: date[2],
    time: time[5],
    team1: team[9],
    team2: team[120],
    winner: team[0],
  },
  {
    id: "A14",
    date: date[2],
    time: time[6],
    team1: team[56],
    team2: team[73],
    winner: team[0],
  },
  {
    id: "A15",
    date: date[2],
    time: time[7],
    team1: team[24],
    team2: team[105],
    winner: team[0],
  },
  {
    id: "A16",
    date: date[2],
    time: time[8],
    team1: team[41],
    team2: team[88],
    winner: team[0],
  },
  {
    id: "A17",
    date: date[3],
    time: time[1],
    team1: team[4],
    team2: team[125],
    winner: team[0],
  },
  {
    id: "A18",
    date: date[3],
    time: time[2],
    team1: team[61],
    team2: team[68],
    winner: team[0],
  },
  {
    id: "A19",
    date: date[3],
    time: time[3],
    team1: team[29],
    team2: team[100],
    winner: team[0],
  },
  {
    id: "A20",
    date: date[3],
    time: time[4],
    team1: team[36],
    team2: team[93],
    winner: team[0],
  },
  {
    id: "A21",
    date: date[3],
    time: time[5],
    team1: team[13],
    team2: team[116],
    winner: team[0],
  },
  {
    id: "A22",
    date: date[3],
    time: time[6],
    team1: team[52],
    team2: team[77],
    winner: team[0],
  },
  {
    id: "A23",
    date: date[3],
    time: time[7],
    team1: team[20],
    team2: team[109],
    winner: team[0],
  },
  {
    id: "A24",
    date: date[3],
    time: time[8],
    team1: team[45],
    team2: team[84],
    winner: team[0],
  },
  {
    id: "A25",
    date: date[4],
    time: time[1],
    team1: team[5],
    team2: team[124],
    winner: team[0],
  },
  {
    id: "A26",
    date: date[4],
    time: time[2],
    team1: team[60],
    team2: team[69],
    winner: team[0],
  },
  {
    id: "A27",
    date: date[4],
    time: time[3],
    team1: team[28],
    team2: team[101],
    winner: team[0],
  },
  {
    id: "A28",
    date: date[4],
    time: time[4],
    team1: team[37],
    team2: team[92],
    winner: team[0],
  },
  {
    id: "A29",
    date: date[4],
    time: time[5],
    team1: team[12],
    team2: team[117],
    winner: team[0],
  },
  {
    id: "A30",
    date: date[4],
    time: time[6],
    team1: team[53],
    team2: team[76],
    winner: team[0],
  },
  {
    id: "A31",
    date: date[4],
    time: time[7],
    team1: team[21],
    team2: team[108],
    winner: team[0],
  },
  {
    id: "A32",
    date: date[4],
    time: time[8],
    team1: team[44],
    team2: team[85],
    winner: team[0],
  },
  {
    id: "A33",
    date: date[5],
    time: time[1],
    team1: team[2],
    team2: team[127],
    winner: team[0],
  },
  {
    id: "A34",
    date: date[5],
    time: time[2],
    team1: team[63],
    team2: team[66],
    winner: team[0],
  },
  {
    id: "A35",
    date: date[5],
    time: time[3],
    team1: team[31],
    team2: team[98],
    winner: team[0],
  },
  {
    id: "A36",
    date: date[5],
    time: time[4],
    team1: team[34],
    team2: team[95],
    winner: team[0],
  },
  {
    id: "A37",
    date: date[5],
    time: time[5],
    team1: team[15],
    team2: team[114],
    winner: team[0],
  },
  {
    id: "A38",
    date: date[5],
    time: time[6],
    team1: team[50],
    team2: team[79],
    winner: team[0],
  },
  {
    id: "A39",
    date: date[5],
    time: time[7],
    team1: team[18],
    team2: team[111],
    winner: team[0],
  },
  {
    id: "A40",
    date: date[5],
    time: time[8],
    team1: team[47],
    team2: team[82],
    winner: team[0],
  },
  {
    id: "A41",
    date: date[6],
    time: time[1],
    team1: team[7],
    team2: team[122],
    winner: team[0],
  },
  {
    id: "A42",
    date: date[6],
    time: time[2],
    team1: team[58],
    team2: team[71],
    winner: team[0],
  },
  {
    id: "A43",
    date: date[6],
    time: time[3],
    team1: team[26],
    team2: team[103],
    winner: team[0],
  },
  {
    id: "A44",
    date: date[6],
    time: time[4],
    team1: team[39],
    team2: team[90],
    winner: team[0],
  },
  {
    id: "A45",
    date: date[6],
    time: time[5],
    team1: team[10],
    team2: team[119],
    winner: team[0],
  },
  {
    id: "A46",
    date: date[6],
    time: time[6],
    team1: team[55],
    team2: team[74],
    winner: team[0],
  },
  {
    id: "A47",
    date: date[6],
    time: time[7],
    team1: team[23],
    team2: team[106],
    winner: team[0],
  },
  {
    id: "A48",
    date: date[6],
    time: time[8],
    team1: team[42],
    team2: team[87],
    winner: team[0],
  },
  {
    id: "A49",
    date: date[7],
    time: time[1],
    team1: team[3],
    team2: team[126],
    winner: team[0],
  },
  {
    id: "A50",
    date: date[7],
    time: time[2],
    team1: team[62],
    team2: team[67],
    winner: team[0],
  },
  {
    id: "A51",
    date: date[7],
    time: time[3],
    team1: team[30],
    team2: team[99],
    winner: team[0],
  },
  {
    id: "A52",
    date: date[7],
    time: time[4],
    team1: team[35],
    team2: team[94],
    winner: team[0],
  },
  {
    id: "A53",
    date: date[7],
    time: time[5],
    team1: team[14],
    team2: team[115],
    winner: team[0],
  },
  {
    id: "A54",
    date: date[7],
    time: time[6],
    team1: team[51],
    team2: team[78],
    winner: team[0],
  },
  {
    id: "A55",
    date: date[7],
    time: time[7],
    team1: team[19],
    team2: team[110],
    winner: team[0],
  },
  {
    id: "A56",
    date: date[7],
    time: time[8],
    team1: team[46],
    team2: team[83],
    winner: team[0],
  },
  {
    id: "A57",
    date: date[8],
    time: time[1],
    team1: team[6],
    team2: team[123],
    winner: team[0],
  },
  {
    id: "A58",
    date: date[8],
    time: time[2],
    team1: team[59],
    team2: team[70],
    winner: team[0],
  },
  {
    id: "A59",
    date: date[8],
    time: time[3],
    team1: team[27],
    team2: team[102],
    winner: team[0],
  },
  {
    id: "A60",
    date: date[8],
    time: time[4],
    team1: team[38],
    team2: team[91],
    winner: team[0],
  },
  {
    id: "A61",
    date: date[8],
    time: time[5],
    team1: team[11],
    team2: team[118],
    winner: team[0],
  },
  {
    id: "A62",
    date: date[8],
    time: time[6],
    team1: team[54],
    team2: team[75],
    winner: team[0],
  },
  {
    id: "A63",
    date: date[8],
    time: time[7],
    team1: team[22],
    team2: team[107],
    winner: team[0],
  },
  {
    id: "A64",
    date: date[8],
    time: time[8],
    team1: team[43],
    team2: team[86],
    winner: team[0],
  },
];

function populateMatches() {
  const tableBody = document.getElementById("matchesTable");
  tableBody.innerHTML = "";
  matches.forEach((match) => {
    const row = document.createElement("tr");
    row.innerHTML = `
              <td>${match.id}</td>
              <td>${match.date}</td>
              <td>${match.time}</td>
              <td>${match.team1}</td>
              <td></td>
              <td>${match.team2}</td>
              <td>${match.winner}<i class="bi bi-check-lg ms-1 text-success"></i></td>`;
    tableBody.appendChild(row);
  });
}
function searchMatches() {
  const input = document.getElementById("searchInput");
  const filter = input.value.toUpperCase();
  const tableBody = document.getElementById("matchesTable");
  const tr = tableBody.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (let i = 0; i < tr.length; i++) {
    let td = tr[i].getElementsByTagName("td"); // Get all cells of the row
    let match = false;
    for (let j = 0; j < td.length; j++) {
      if (td[j] && td[j].textContent.toUpperCase().indexOf(filter) > -1) {
        match = true;
        break;
      }
    }
    tr[i].style.display = match ? "" : "none";
  }
}

// Populate matches when the page loads
document.addEventListener("DOMContentLoaded", function () {
  populateMatches();
});
